Hw5.1
MihailKulikov/MyHomeworksSem3 pull request #7
Opened 2020-11-09 16:34 UTC by MihailKulikov

2020-12-06 14:20 UTC, yurii-litvinov requested changes
В целом система с Handler-ами, кажется, овердизайн. Это можно не переделывать, но в продакшене такой код лучше не писать, он вводит дополнительный уровень "indirection", так что прямо в коде не видно, что в какой последовательности происходит, надо найти какой-то другой класс и там посмотреть. Это ООПшно и всё такое, но разобраться в программе сложнее, а надо, чтобы разобраться было просто.

2020-12-06 14:20 UTC, yurii-litvinov commented on sem3/MyNUnit/Attributes/BeforeAttribute.cs
> +    /// Identifies a method to be called immediately after each test is run.
Неправда :)

2020-12-06 14:20 UTC, yurii-litvinov commented on sem3/MyNUnit/Attributes/AfterClassAttribute.cs
> +    /// Identifies a static method that is called once to perform setup before test class initialization.
Что-то before и after в комментариях перепутаны

2020-12-06 14:20 UTC, yurii-litvinov commented on sem3/MyNUnit/Runner/AssemblyHandler.cs
> +                })
Стоило бы это тоже параллельно делать, загрузка сборки потенциально трудоёмка и легко параллелится

2020-12-06 14:20 UTC, yurii-litvinov commented on sem3/MyNUnit/Runner/RunnerCli.cs
> +            string path = (await textReader.ReadLineAsync())!;
Хотелось бы всё-таки путь до сборок принимать как аргумент командной строки, а не вводить с консоли, иначе в CI, например, такой раннер было бы неудобно использовать.

2020-12-06 14:20 UTC, yurii-litvinov commented on sem3/MyNUnit/Runner/Runner.cs
> +            testClasses.Select(testClass =>
Надо же по условию тесты параллельно запускать, а тут если у нас сотня классов, и в каждом по одному тесту, будет печаль

2020-12-06 14:20 UTC, yurii-litvinov commented on sem3/MyNUnit/Runner/TestClassHandlers/AfterHandler.cs
> +                    afterMethod => afterMethod.Invoke(testClass.TestClassInstance, null));
А вот тут я бы не стал After-методы все параллельно запускать, потому что тогда пользователю надо будет бояться гонок. Да и вообще бы запретил больше одного After, но дело вкуса

2020-12-06 14:20 UTC, yurii-litvinov commented on sem3/MyNUnit/Runner/TestClassHandlers/TestHandler.cs
> +            if (!testClass.TestMethodInfos.TryDequeue(out var testMethod)) return true;
Лучше всё-таки
```csharp
if (!testClass.TestMethodInfos.TryDequeue(out var testMethod)) 
{
    return true;
}
```

2020-12-06 14:20 UTC, yurii-litvinov commented on sem3/MyNUnit/Runner/TestClassWrapper.cs
> +        public object? TestClassInstance => testClassLazyInstance.Value;
Так получится, что единожды созданный экземпляр используется для всех тестов, а с учётом того, что тесты запускаются параллельно, это может привести к хаосу (гонкам прямо внутри тестового класса). Правильно --- создавать новый экземпляр для каждого теста, и на нём уже прогонять Before/After. Так, кстати, большинство библиотек модульного тестирования и делают

2020-12-06 14:20 UTC, yurii-litvinov commented on sem3/MyNUnit/Runner/TestClassWrapper.cs
> +                .Where(info => info.GetCustomAttributes<TestAttribute>().Any()));
Ещё где-то надо проверять корректность самих тестов --- не принимают ли тестовые методы значения, не возвращают ли результат, не имеют ли не по делу других модификаторов типа static и т.д.

2020-12-31 03:12 UTC, MihailKulikov commented on sem3/MyNUnit/Attributes/BeforeAttribute.cs
> +    /// Identifies a method to be called immediately after each test is run.
fixed

2020-12-31 03:14 UTC, MihailKulikov commented on sem3/MyNUnit/Attributes/AfterClassAttribute.cs
> +    /// Identifies a static method that is called once to perform setup before test class initialization.
fixed

2020-12-31 03:17 UTC, MihailKulikov commented on sem3/MyNUnit/Runner/AssemblyHandler.cs
> +                })
fixed

2020-12-31 03:34 UTC, MihailKulikov commented on sem3/MyNUnit/Runner/RunnerCli.cs
> +            string path = (await textReader.ReadLineAsync())!;
fixed

2020-12-31 03:37 UTC, MihailKulikov commented on sem3/MyNUnit/Runner/Runner.cs
> +            testClasses.Select(testClass =>
fixed

2020-12-31 03:39 UTC, MihailKulikov commented on sem3/MyNUnit/Runner/TestClassHandlers/AfterHandler.cs
> +                    afterMethod => afterMethod.Invoke(testClass.TestClassInstance, null));
fixed

2020-12-31 03:39 UTC, MihailKulikov commented on sem3/MyNUnit/Runner/TestClassHandlers/TestHandler.cs
> +            if (!testClass.TestMethodInfos.TryDequeue(out var testMethod)) return true;
fixed

2020-12-31 03:51 UTC, MihailKulikov commented on sem3/MyNUnit/Runner/TestClassWrapper.cs
> +        public object? TestClassInstance => testClassLazyInstance.Value;
fixed

2020-12-31 04:00 UTC, MihailKulikov commented on sem3/MyNUnit/Runner/TestClassWrapper.cs
> +                .Where(info => info.GetCustomAttributes<TestAttribute>().Any()));
fixed

2021-01-02 12:52 UTC, yurii-litvinov requested changes

2021-01-02 12:52 UTC, yurii-litvinov commented on sem3/MyNUnit/Runner/Program.cs
> +                Console.WriteLine("Incorrect number of arguments.");
По-хорошему, надо бы выводить какой-то хелп, как делают все консольные утилиты

2021-01-02 12:52 UTC, yurii-litvinov commented on sem3/MyNUnit/Runner/RunnerCli.cs
> +            await textWriter.WriteLineAsync(IntroduceMessage);
Думаю, что это уже не нужно

2021-01-02 12:52 UTC, yurii-litvinov commented on sem3/MyNUnit/Runner/TestClassWrapper.cs
> +                num => { testClassInstances.Enqueue(Activator.CreateInstance(classType)); });
Можно было просто создавать экземпляр непосредственно перед запуском теста, было бы проще

2021-01-02 12:52 UTC, yurii-litvinov commented on sem3/MyNUnit/Runner/TestClassWrapper.cs
> +            testClassInstances.TryDequeue(out var testClassInstance) ? testClassInstance : null;
И что-то я не понял, BeforeHandler и TestHandler получают каждый свой testClassInstance, что ли?

2021-01-03 09:02 UTC, yurii-litvinov approved these changes
Ага, вот теперь всё ок. Зачтена

2021-01-04 04:53 UTC, merged